# mdns-repeater only requires the interface names and it will do the rest.
# For example, the dd-wrt standard installation defines br0 for the wireless
# interface and vlan1 as the WAN interface.
OPTIONS="br0 vlan1"
